version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
    php:
        build:
            context: php-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: 
            context: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
